name: run tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest --junit-xml=junit.xml -o junit_family=xunit1

      - name: Upload Test Results to Trunk.io
        if: '!cancelled()' # Upload the results even if the tests fail
        continue-on-error: true # don't fail this job if the upload fails
        uses: trunk-io/analytics-uploader@v1
        with:
          junit-paths: "**/junit.xml"
          org-slug: <TRUNK_ORG_URL_SLUG>
          token: ${{ secrets.TRUNK_API_TOKEN }}
