name: run tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Upload Tests
    runs-on: ubuntu-latest

    steps:
      - name: Run Tests
        run: ...

      - name: Upload Test Results to Trunk.io
        if: '!cancelled()' # Upload the results even if the tests fail
        continue-on-error: true # don't fail this job if the upload fails
        uses: trunk-io/analytics-uploader@v1
        with:
          junit-paths: "**/junit.xml"        
          org-slug: <TRUNK_ORG_URL_SLUG>
          token: ${{ secrets.TRUNK_API_TOKEN }}
